### ISSUE TITLE
Review all English texts and fix typos in "PAss Private Assisted House" file

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-user-manual#10]
We are not native English speakers and the documentation really needs some external proofreading.
File to review is https://github.com/freedomotic/fd-user-manual/blob/master/docs/source/use-cases/pass-project.rst

**Comment by Jpfonseca** [comment]
@mcicolella  can I be assigned to do this ??

**Comment by mcicolella** [comment]
@Jpfonseca ok.
