### ISSUE TITLE
Review all English texts and fix typos in "SpokenHouse" file

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-user-manual#11]
We are not native English speakers and the documentation really needs some external proofreading.
File to review is https://github.com/freedomotic/fd-user-manual/blob/master/docs/source/use-cases/spokenhouse.rst

**Comment by Ilozuluchris** [comment]
@mcicolella Can I take this

**Comment by Zeustopher** [comment]
@mcicolella - I'll take this one on.

**Comment by Zeustopher** [comment]
This is resolved in https://github.com/freedomotic/fd-user-manual/pull/16

Happy Hacktoberfest!
