### ISSUE TITLE
Review all English texts and fix typos in "The project" section

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-user-manual#3]
We are not native English speakers and the documentation really needs some external proofreading.
Pages to review are in ["The project"](https://github.com/freedomotic/fd-user-manual/tree/master/docs/source/the-project) folder.

If you choose one or more pages please comment.

**Comment by Zeustopher** [comment]
I would like to update the [Project History](https://github.com/freedomotic/fd-user-manual/blob/master/docs/source/the-project/project-history.rst )

Happy Hacktoberfest!

**Comment by Zeustopher** [comment]
Pull Request for Project History: https://github.com/freedomotic/fd-user-manual/pull/4

**Comment by mcicolella** [comment]
@Zeustopher PR #4 integrated. Thanks

**Comment by mcicolella** [comment]
The last page to review is how-to-contribute.rst.
If it's ok for you we can close this issue.

**Comment by Zeustopher** [comment]
@mcicolella - I've updated that final file. There wasn't a whole lot to do on it so I just updated some of the wording and formatting. Hopefully you like the changes. If you do, then this issue can be closed.

Happy Hacktoberfest!

**Comment by mcicolella** [comment]
I'm closing this issue. Thanks to all for your great support.
