### ISSUE TITLE
Review all English texts and fix typos in "Sed" file

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-user-manual#5]
We are not native English speakers and the documentation really needs some external proofreading.
The page to review is [sed.rst](https://github.com/freedomotic/fd-user-manual/blob/master/docs/source/use-cases/sed.rst).

**Comment by rishz** [comment]
Hi! I would like to update the documentation.

**Comment by rishz** [comment]
Pull Request for sed.rst #6.

**Comment by murphytrueman** [comment]
Hi @mcicolella I'd love to help out if you still need someone to look over the text.

**Comment by mcicolella** [comment]
@murphytrueman this issue has been fixed in 5fc7283ec90802452e7b1adc75bf2ca26ba64b3e but I'll publish new issues soon.
